import { Apartment } from '@/types/apartment';

export const mockApartments: Apartment[] = [
  {
    _id: '1',
    url: 'https://streeteasy.com/building/123-main-st',
    address: '123 Main Street, Apt 4B',
    neighborhood: 'Upper East Side',
    borough: 'Manhattan',
    price: 3200,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 850,
    description: 'Bright and spacious 2BR apartment with updated kitchen, hardwood floors throughout, and excellent natural light. Close to subway and parks.',
    amenities: ['Doorman', 'Elevator', 'Laundry in building', 'Dishwasher'],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    noFee: true,
    rentStabilized: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '2',
    url: 'https://streeteasy.com/building/456-park-ave',
    address: '456 Park Avenue, Apt 12A',
    neighborhood: 'Midtown',
    borough: 'Manhattan',
    price: 4500,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 650,
    description: 'Luxury doorman building with stunning city views. Modern renovations, central AC, and rooftop access.',
    amenities: ['Doorman', 'Elevator', 'Gym', 'Roof deck', 'Central AC', 'Concierge'],
    images: [
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    ],
    noFee: false,
    rentStabilized: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '3',
    url: 'https://streeteasy.com/building/789-brooklyn-st',
    address: '789 Brooklyn Street, Unit 2',
    neighborhood: 'Williamsburg',
    borough: 'Brooklyn',
    price: 2800,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 550,
    description: 'Charming 1BR in the heart of Williamsburg. Exposed brick, high ceilings, and tons of character. Steps from restaurants and nightlife.',
    amenities: ['Laundry in building', 'Pet friendly', 'Bike room'],
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1560185127-6a8c72a1c4b9?w=800',
    ],
    noFee: true,
    rentStabilized: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '4',
    url: 'https://streeteasy.com/building/101-chelsea-pl',
    address: '101 Chelsea Place, Apt 8C',
    neighborhood: 'Chelsea',
    borough: 'Manhattan',
    price: 3800,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    description: 'Stunning 2BR/2BA in prime Chelsea location. Chef\'s kitchen with stainless appliances, in-unit laundry, and private outdoor space.',
    amenities: ['Elevator', 'Laundry in unit', 'Dishwasher', 'Outdoor space', 'Central AC'],
    images: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
      'https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800',
    ],
    noFee: false,
    rentStabilized: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '5',
    url: 'https://streeteasy.com/building/202-park-slope',
    address: '202 Park Slope Avenue, Garden',
    neighborhood: 'Park Slope',
    borough: 'Brooklyn',
    price: 2400,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 600,
    description: 'Garden level 1BR with private backyard access. Quiet tree-lined street, close to Prospect Park. Perfect for pet owners.',
    amenities: ['Outdoor space', 'Pet friendly', 'Storage'],
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    noFee: true,
    rentStabilized: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '6',
    url: 'https://streeteasy.com/building/303-harlem',
    address: '303 West 125th Street, Apt 6D',
    neighborhood: 'Harlem',
    borough: 'Manhattan',
    price: 1950,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 750,
    description: 'Affordable 2BR in historic Harlem building. Recently renovated with new appliances. Near A/B/C/D trains.',
    amenities: ['Elevator', 'Laundry in building'],
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    noFee: true,
    rentStabilized: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '7',
    url: 'https://streeteasy.com/building/404-lic',
    address: '404 Center Boulevard, Apt 45F',
    neighborhood: 'Long Island City',
    borough: 'Queens',
    price: 3500,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 700,
    description: 'High-floor 1BR with floor-to-ceiling windows and spectacular Manhattan skyline views. Full amenity building.',
    amenities: ['Doorman', 'Elevator', 'Gym', 'Roof deck', 'Central AC', 'Concierge', 'Parking'],
    images: [
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    noFee: false,
    rentStabilized: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '8',
    url: 'https://streeteasy.com/building/505-greenpoint',
    address: '505 Manhattan Avenue, 3R',
    neighborhood: 'Greenpoint',
    borough: 'Brooklyn',
    price: 2600,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 900,
    description: 'Spacious railroad-style 2BR with original details. Sunny exposure, steps from McCarren Park and G train.',
    amenities: ['Pet friendly', 'Bike room'],
    images: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    noFee: true,
    rentStabilized: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '9',
    url: 'https://streeteasy.com/building/606-village',
    address: '606 Bleecker Street, Apt 2B',
    neighborhood: 'Greenwich Village',
    borough: 'Manhattan',
    price: 4200,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 500,
    description: 'Charming pre-war 1BR in the heart of the Village. Exposed brick, decorative fireplace, tree-lined street views.',
    amenities: ['Laundry in building', 'Dishwasher'],
    images: [
      'https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800',
      'https://images.unsplash.com/photo-1560185127-6a8c72a1c4b9?w=800',
    ],
    noFee: false,
    rentStabilized: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '10',
    url: 'https://streeteasy.com/building/707-astoria',
    address: '707 Steinway Street, Apt 5A',
    neighborhood: 'Astoria',
    borough: 'Queens',
    price: 2200,
    bedrooms: 2,
    bathrooms: 1,
    sqft: 850,
    description: 'Sun-drenched corner 2BR with eat-in kitchen. Close to N/W trains, restaurants, and Astoria Park.',
    amenities: ['Elevator', 'Laundry in building', 'Pet friendly'],
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    ],
    noFee: true,
    rentStabilized: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '11',
    url: 'https://streeteasy.com/building/808-dumbo',
    address: '808 Water Street, Apt 12B',
    neighborhood: 'DUMBO',
    borough: 'Brooklyn',
    price: 5200,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    description: 'Stunning loft conversion with 14ft ceilings, exposed brick, and breathtaking bridge views. Full-service building.',
    amenities: ['Doorman', 'Elevator', 'Gym', 'Laundry in unit', 'Roof deck', 'Central AC', 'Storage'],
    images: [
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    noFee: false,
    rentStabilized: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '12',
    url: 'https://streeteasy.com/building/909-fidi',
    address: '909 Wall Street, Apt 33C',
    neighborhood: 'Financial District',
    borough: 'Manhattan',
    price: 3900,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 650,
    description: 'Modern high-rise with harbor views. Building features 24/7 concierge, pool, and fitness center.',
    amenities: ['Doorman', 'Elevator', 'Gym', 'Central AC', 'Concierge'],
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    noFee: false,
    rentStabilized: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
